apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-pod-dep
spec:
  selector:
    matchLabels:
      server: pod-to-pod
  replicas: 2
  template:
    metadata:
      labels:
        server: pod-to-pod
    spec:
      containers:
        - name: server-container
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP