dns_servers:
  - 8.8.8.8

docker_http_proxy: http://147.11.252.42:9090
docker_https_proxy: http://147.11.252.42:9090

external_oam_subnet: 10.10.10.0/24
external_oam_gateway_address: 10.10.10.1
external_oam_floating_address: 10.10.10.3

ansible_become_pass: ANSIBLE_PASS
admin_password: ADMIN_PASS
